export const START_SPINNER = "START_SPINNER";
export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PAGINATED_PRODUCT = "GET_PAGINATED_PRODUCT"
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const PRODUCT_ERROR = "PRODUCT_ERROR"